include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    one_member_abstracts: false
