name: my_location_bloc_clean
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.0
  intl: any
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.0
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
